[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.2.2", features = ["js"] }

[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"

[lib]
path="src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]

[build-dependencies]
slint-build = "1.8.0"