[package]
name = "vector_drawing_webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
log = "0.4"
console_log = "1.0.0"
svgtypes = "0.15.3"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3.77"
features = ["Window", "Document", "HtmlCanvasElement", "HtmlElement", "HtmlInputElement", "HtmlImageElement", "MouseEvent", "WheelEvent", "KeyboardEvent", "CanvasGradient"
, "CanvasRenderingContext2d", "DomRect", "DragEvent", "DataTransfer", "FileReader", "HtmlDivElement", "Path2d", "Element", "DomParser", "SupportedType", "Node", "NodeList"
, "CssStyleDeclaration", "HtmlCollection", "HtmlStyleElement" ]